### Código utilizado en el video:
https://youtu.be/1AUNxUTdr8o

In [ ]:
import numpy as np

In [ ]:
array_unos = np.ones(8)
print(array_unos)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
array_aleatorio1 = np.random.random(8)
print(array_aleatorio1)

[0.71460777 0.68468994 0.04236689 0.28102415 0.97642868 0.33126787
 0.25017022 0.35968594]


In [ ]:
array_aleatorio2 = np.random.randint(10,size=8)
print(array_aleatorio2)

[3 1 7 1 9 3 8 7]


# Suma

In [ ]:
suma_1 = array_unos + array_aleatorio1
print(suma_1)

[1.71460777 1.68468994 1.04236689 1.28102415 1.97642868 1.33126787
 1.25017022 1.35968594]


In [ ]:
suma_2 = np.sum(array_aleatorio2)
print(suma_2)

39


# Resta

In [ ]:
resta_1 = suma_1 - array_unos
print(resta_1)

[0.71460777 0.68468994 0.04236689 0.28102415 0.97642868 0.33126787
 0.25017022 0.35968594]


In [ ]:
resta_2 = np.subtract(suma_1, array_unos)
print(resta_2)

[0.71460777 0.68468994 0.04236689 0.28102415 0.97642868 0.33126787
 0.25017022 0.35968594]


In [ ]:
array_subs = np.subtract(array_aleatorio2, 1)
print(array_subs)

[2 0 6 0 8 2 7 6]


# Multiplicación

In [ ]:
producto_1 = array_aleatorio1 * array_aleatorio2
print(producto_1)

[2.1438233  0.68468994 0.2965682  0.28102415 8.78785809 0.99380362
 2.00136175 2.51780156]


In [ ]:
producto_2 = np.multiply(array_aleatorio1, array_aleatorio2)
print(producto_2)

[2.1438233  0.68468994 0.2965682  0.28102415 8.78785809 0.99380362
 2.00136175 2.51780156]


In [ ]:
producto_3 = np.multiply(array_subs, 3)
print(producto_3)

[ 6  0 18  0 24  6 21 18]


# Negativos

In [ ]:
negativo = np.negative(producto_3)
print(negativo)

[ -6   0 -18   0 -24  -6 -21 -18]


# Elevar al cuadrado

In [ ]:
cuadrado = np.square(negativo)
print(cuadrado)

[ 36   0 324   0 576  36 441 324]


# Raíz cuadrada

In [ ]:
raiz = np.sqrt(cuadrado)
print(raiz)

[ 6.  0. 18.  0. 24.  6. 21. 18.]
