### Código utilizado en el video:
https://youtu.be/3lAdW03QQVQ

In [ ]:
import numpy as np

# .ones()

In [ ]:
array_1 = np.ones(8)

In [ ]:
print(array_1)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
print(type(array_1))

<class 'numpy.ndarray'>


In [ ]:
print(type(array_1[0]))

<class 'numpy.float64'>


In [ ]:
array_2 = np.ones(4, dtype=int)
print(array_2)

[1 1 1 1]


In [ ]:
print(type(array_2[0]))

<class 'numpy.int32'>


In [ ]:
array_3 = np.ones([3,3])

In [ ]:
print(array_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# ones_like()

In [ ]:
lista_1 = [2,3,4,3,2,5]
array_4 = np.ones_like(lista_1)
print(array_4)

[1 1 1 1 1 1]


In [ ]:
matriz = [[10, 3, 2],[3, 8, 5],[10,11,13]]
print(matriz)

[[10, 3, 2], [3, 8, 5], [10, 11, 13]]


In [ ]:
array_5 = np.ones_like(matriz)
print(array_5)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
