### Código utilizado en el video:
https://youtu.be/cvn_Da4pIP4

In [ ]:
import numpy as np

# .linspace()

In [ ]:
array_1 = np.linspace(0, 100, num=5)

In [ ]:
print(array_1)

[  0.  25.  50.  75. 100.]


In [ ]:
print(type(array_1))

<class 'numpy.ndarray'>


In [ ]:
array_2 = np.linspace(0, 20, num=5)

In [ ]:
print(array_2)

[ 0.  5. 10. 15. 20.]


In [ ]:
array_3 = np.linspace(0, 20)

In [ ]:
print(array_3)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [ ]:
array_4 = np.linspace(0,100, num=4, endpoint=False)

In [ ]:
print(array_4)

[ 0. 25. 50. 75.]


In [ ]:
print(array_1)

[  0.  25.  50.  75. 100.]


In [ ]:
print(type(array_1[0]))

<class 'numpy.float64'>


In [ ]:
array_1 = np.linspace(0, 100, num=5, dtype=int)

In [ ]:
print(array_1)

[  0  25  50  75 100]


In [ ]:
print(type(array_1[0]))

<class 'numpy.int32'>


# .arange()

In [ ]:
array_5 = np.arange(1,10,1)

In [ ]:
print(array_5)

[1 2 3 4 5 6 7 8 9]


In [ ]:
array_6 = np.arange(1,10, 0.5)

In [ ]:
print(array_6)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [ ]:
array_7 = np.arange(1,10,0.3)

In [ ]:
print(array_7)

[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1
 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]


In [ ]:
array_8 = np.arange(1,10,1, dtype=float)

In [ ]:
print(array_8)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
