### Código utilizado en el video:
https://youtu.be/K1dGEyxjijc

In [ ]:
import numpy as np

# .zeros()

In [ ]:
array_1 = np.zeros(8)

In [ ]:
print(array_1)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(type(array_1))

<class 'numpy.ndarray'>


In [ ]:
print(type(array_1[0]))

<class 'numpy.float64'>


In [ ]:
array_2 = np.zeros(4, dtype=int)
print(array_2)

[0 0 0 0]


In [ ]:
print(type(array_2[0]))

<class 'numpy.int32'>


In [ ]:
array_3 = np.zeros([3,3])

In [ ]:
print(array_3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# zeros_like()

In [ ]:
lista_1 = [2,3,4,3,2,5]
array_4 = np.zeros_like(lista_1)
print(array_4)

[0 0 0 0 0 0]


In [ ]:
matriz = [[10, 3, 2],[3, 8, 5],[10,11,13]]
print(matriz)

[[10, 3, 2], [3, 8, 5], [10, 11, 13]]


In [ ]:
array_5 = np.zeros_like(matriz)
print(array_5)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
