### Código utilizado en el video:
https://youtu.be/1XGbbuodJUs

In [ ]:
import numpy as np

# random.random()

In [ ]:
valor_1 = np.random.random()
print(valor_1)

0.9580919555802048


In [ ]:
print(type(valor_1))

<class 'float'>


In [ ]:
array_1 = np.random.random(5)
print(array_1)

[0.93512954 0.72216654 0.91729076 0.37734535 0.44298797]


In [ ]:
print(type(array_1))

<class 'numpy.ndarray'>


In [ ]:
matriz_1 = np.random.random((3,3))
print(matriz_1)

[[0.19706616 0.88259208 0.64203623]
 [0.61307309 0.02819317 0.71824249]
 [0.65977236 0.45648839 0.62315494]]


# random.randint()

In [ ]:
valor_2 = np.random.randint(100)
print(valor_2)

85


In [ ]:
valor_3 = np.random.randint(100)
print(valor_3)

97


In [ ]:
valor_5 = np.random.randint(85,100)
print(valor_5)

88


In [ ]:
valor_6 = np.random.randint(75,100)
print(valor_6)

91


In [ ]:
array_2 = np.random.randint(75,100, 4)
print(array_2)

[76 97 78 89]


In [ ]:
print(type(array_2))

<class 'numpy.ndarray'>


In [ ]:
matriz_2 = np.random.randint(75,100, (5,5))
print(matriz_2)

[[96 78 78 90 81]
 [84 95 87 80 81]
 [80 94 81 92 81]
 [86 97 79 99 94]
 [89 77 95 94 91]]


In [ ]:
print(type(matriz_2))

<class 'numpy.ndarray'>
